# Generated by Django 5.2.6 on 2025-10-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blossom', '0002_category_alter_product_options_product_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text="The product's main category.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Blossom.category'),
        ),
    ]
