# Generated by Django 5.2.6 on 2025-10-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blossom', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
